DutchTreat/Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DutchTreat.Data;
using DutchTreat.Services;
using DutchTreat.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DutchTreat.Controllers
{
    public class AppController : Controller
    {
        private readonly IMailService _mailService;
        private readonly IDutchRepository _repository;

        public AppController(IMailService mailService, IDutchRepository repository)
        {
            _mailService = mailService;
            _repository = repository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("contact")]
        public IActionResult Contact()
        {
            
            return View();
        }

        [HttpPost("contact")]
        public IActionResult Contact(ContactViewModel model)
        {
            if (ModelState.IsValid)
            {
                _mailService.SendMessage("alexanderashraf@gmail.com", model.Subject, $"From: {model.Name} - {model.Email}, Message: {model.Message}");
                ViewBag.UserMessage = "Mail Sent";
                ModelState.Clear();
            }

            return View();
        }

        public IActionResult About()
        {
            ViewBag.Title = "Contact Us";

            return View();
        }

        public IActionResult Shop()
        {
            var results = _repository.GetAllProducts();
            return View(results);
        }
    }
}

DutchTreat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <title>Dutch Treat: @ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/sitestyle.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse">
        <header class="container">
            <div class="navbar-header">
                <div class="navbar-brand"><i class="fa fa-paint-brush"></i>Dutch Treat</div>
                <button class="navbar-toggle" data-toggle="collapse" data-target="#menu">&#9776;</button>
            </div>
            <div id="menu" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="App" asp-action="Index">Home</a></li>
                    <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
                    <li><a asp-controller="App" asp-action="About">About</a></li>
                </ul>
            </div>
        </header>
    </div>
    <section class="container">
        <h2 class="text-center">@ViewBag.Title</h2>
        @RenderBody()
    </section>
    <footer class="container">
        <div class="text-center">Copyright 2017 Dutch Treat LLC</div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/index.js"></script>
    @RenderSection("scripts", false)
</body>
</html>